### PR TITLE
Update nginx.tmpl

### PR DESCRIPTION
**Pull request by kkellerlbl**
Please do not merge yet!

Merge manual configuration of front-facing nginx proxy with deploy_tools config template.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
I think this looks good, okay to merge by me.  But I'd like others to look at it before merging.

**Comment by kkellerlbl** [comment]
Applies to https://atlassian.kbase.us/browse/KBASE-2000 .

**Comment by scanon** [comment]
I'm debating if the full nginx template should live with the repo or not.  It is almost like a local customization.

**Comment by danielolson5** [comment]
My opinion is the template lives in the repo - but static/manual modifications live in deployment.cfg.  We'd need to test storing this in a key though. 

Dan

**Comment by sychan** [comment]
Does this still matter?

**Pull request closed without merging**
